### ISSUE TITLE
获取html 的规则是什么呢，我想用java 写一套爬虫只取url

### ISSUE THREAD

**Issue by tianshaokai** [ihanyang/meizi#1]

**Comment by ihanyang** [comment]
没有什么规则啊，就是获取 html 页面，然后正则匹配 img

**Comment by tianshaokai** [comment]
node还不熟， 我想用java jsoup 去解析获取试试，今天试试了作者的npm 包，爬取的很慢，不知道是不是公司网有问题，并且下载的图片有的不能看，nodejs 的版本 4.x  是否可以运行呢

**Comment by ihanyang** [comment]
我用的 6.x 。4.x 没有测试

**Comment by tianshaokai** [comment]
大神们 分页的地方是怎么获取的呢，我用jsoup 不知道怎么获取分页的地方

**Comment by tianshaokai** [comment]
Elements links = doc.select("div.pagenavi span");
  System.out.println(links.get(6).text());  我是获取的div 下所有span 然后下标为6的span，看了你代码正则写的很复杂没看明白 希望大神说说这个地方怎么获取呢

**Comment by ihanyang** [comment]
就是先获取每种类型的的妹纸总数，然后累加就行了
